### PR TITLE
Data connection

### PR DESCRIPTION
**Pull request by ghost**
Can someone review my changes

### CODE REVIEW

**Review by simondereuver — CHANGES_REQUESTED** [review]
Check my comments and fix the empty if-case.

**Review by ivonilsson — CHANGES_REQUESTED** [review]
Fix the if condition in RevieveDataFromServer()

**Review by Pramell94 — APPROVED** [review]
LGMT!

**Review by OskarSundberg — APPROVED** [review]

**Review by Pramell94 — APPROVED** [review]

**Review by OskarSundberg — APPROVED** [review]
lgtm

**Review by ivonilsson — APPROVED** [review]
LGTM! 👍

**Review by simondereuver — APPROVED** [review]
Nice!

**Pull request merged**
